FROM trufflesuite/ganache-cli:latest

EXPOSE 8545

CMD ["--host", "0.0.0.0", "--port", "8545", "--deterministic", "--mnemonic", "myth like bonus scare over problem client lizard pioneer submit female collect"]